version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      DATABASE_HOST: ${DB_HOST}
      PGUSER: ${DB_USERNAME}
    ports:
      - ${DB_PORT}
    healthcheck:
      test: "pg_isready -h postgres"
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - application
  go-api:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - api:/usr/src/app/
    networks:
      - application

volumes:
  api:
  database_postgres:

# Networks to be created to facilitate communication between containers
networks:
  application:
    driver: bridge
